// ============================================================
// BANCA DE ÎNTREBĂRI - Morfologie Dentară
// Focus: aliniere, aspect, compoziție, rădăcini, cuspizi, șanțuri
// ============================================================
const QUESTIONS = [
  // ===== COMPOZIȚIE ȚESUTURI (15) =====
  { c:"Compoziție", q:"Care este compoziția procentuală a smalțului?", o:["95% hidroxiapatită, 4% apă, 1% organice","70% hidroxiapatită, 12% apă, 18% organice","65% hidroxiapatită, 23% organice, 12% apă","50% hidroxiapatită, 25% apă, 25% organice"], a:0 },
  { c:"Compoziție", q:"Care este compoziția procentuală a dentinei?", o:["95% anorganic, 4% apă, 1% organic","70% anorganic, 12% apă, 18% organic","65% anorganic, 23% organic, 12% apă","80% anorganic, 10% apă, 10% organic"], a:1 },
  { c:"Compoziție", q:"Care este compoziția procentuală a cementului?", o:["95% hidroxiapatită, 4% apă, 1% organice","70% hidroxiapatită, 12% apă, 18% organice","65% hidroxiapatită, 23% organice, 12% apă","50% hidroxiapatită, 25% apă, 25% organice"], a:2 },
  { c:"Compoziție", q:"Care țesut dentar este cel mai dur din organism?", o:["Dentina","Cementul","Smalțul","Pulpa"], a:2 },
  { c:"Compoziție", q:"Care țesut dentar are cea mai apropiată structură de țesutul osos?", o:["Smalțul","Dentina","Cementul","Pulpa"], a:2 },
  { c:"Compoziție", q:"Care țesut dentar se formează DOAR în perioada embrionară?", o:["Dentina","Cementul","Smalțul","Pulpa"], a:2 },
  { c:"Compoziție", q:"Care țesut se formează pe toată durata vieții dintelui?", o:["Smalțul","Dentina și cementul","Doar smalțul","Doar cementul"], a:1 },
  { c:"Compoziție", q:"Smalțul este sintetizat de:", o:["Odontoblaste","Ameloblaste","Cementoblaști","Fibroblaști"], a:1 },
  { c:"Compoziție", q:"Dentina este sintetizată de:", o:["Odontoblaste","Ameloblaste","Cementoblaști","Fibroblaști"], a:0 },
  { c:"Compoziție", q:"Cementul este sintetizat de:", o:["Odontoblaste","Ameloblaste","Cementoblaști","Fibroblaști"], a:2 },
  { c:"Compoziție", q:"Smalțul provine embriologic din:", o:["Mezoderm","Ectoderm","Endoderm","Mezenchim"], a:1 },
  { c:"Compoziție", q:"Dentina și cementul provin embriologic din:", o:["Ectoderm","Mezoderm","Endoderm","Neuroectoderm"], a:1 },
  { c:"Compoziție", q:"Care este grosimea smalțului la nivelul cuspizilor?", o:["0,5 mm","1 mm","1,5 mm","2,5 mm"], a:3 },
  { c:"Compoziție", q:"Care este grosimea smalțului la nivelul coletului?", o:["0,5 mm","1 mm","1,5 mm","2,5 mm"], a:0 },
  { c:"Compoziție", q:"Dentina terțiară se formează:", o:["În timpul odontogenezei","Fiziologic după odontogeneză","Ca mecanism de apărare la stimuli patologici","Doar embrionar"], a:2 },
  { c:"Compoziție", q:"Ce procent de apă conține smalțul?", o:["1%","4%","12%","23%"], a:1 },
  { c:"Compoziție", q:"Ce procent de apă conține dentina?", o:["1%","4%","12%","23%"], a:2 },
  { c:"Compoziție", q:"Ce procent de apă conține cementul?", o:["1%","4%","12%","23%"], a:2 },
  { c:"Compoziție", q:"Ce procent de substanțe organice conține smalțul?", o:["1%","4%","12%","23%"], a:0 },
  { c:"Compoziție", q:"Ce procent de substanțe organice conține dentina?", o:["1%","4%","18%","23%"], a:2 },
  { c:"Compoziție", q:"Ce procent de substanțe organice conține cementul?", o:["1%","4%","12%","23%"], a:3 },
  { c:"Compoziție", q:"Substanța organică dominantă din dentină este:", o:["Colagenul","Elastina","Cheratina","Mucina"], a:0 },
  { c:"Compoziție", q:"Substanța organică dominantă din cement este:", o:["Colagenul","Elastina","Cheratina","Mucina"], a:0 },
  { c:"Compoziție", q:"Cristalele din smalț sunt sub formă de:", o:["Prisme de hidroxiapatită","Fibre de colagen","Tubuli dentinari","Lacune"], a:0 },
  { c:"Compoziție", q:"Dentina este traversată de:", o:["Prisme","Tubuli dentinari","Lacune","Canale Havers"], a:1 },
  { c:"Compoziție", q:"Fibrele Tomes reprezintă:", o:["Prelungiri ale odontoblaștilor în tubulii dentinari","Fibre de colagen din smalț","Fibre nervoase din cement","Fibre elastice din pulpă"], a:0 },
  { c:"Compoziție", q:"Densitatea tubulilor dentinari este mai mare:", o:["Spre periferie","Spre camera pulpară","Uniform","Doar la colet"], a:1 },
  { c:"Compoziție", q:"Dentina secundară are structură:", o:["Identică cu cea primară","Regulată","Neregulată dar cu aceleași structuri ca primară","Fără canaliculi"], a:2 },
  { c:"Compoziție", q:"Dentina terțiară are structură:", o:["Regulată","Fără canaliculi, total neregulată","Identică cu primară","Amorfă"], a:1 },
  { c:"Compoziție", q:"Joncțiunea amelo-cementară se poate realiza în:", o:["2 moduri","3 moduri","4 moduri","5 moduri"], a:1 },

  // ===== RĂDĂCINI (20) =====
  { c:"Rădăcini", q:"Câte rădăcini are incisivul central superior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are incisivul lateral superior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are caninul superior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 1 superior?", o:["1 (uneori 2)","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 2 superior?", o:["1 (uneori 2)","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 1 superior?", o:["1","2","3","4"], a:2 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 2 superior?", o:["1","2","3","4"], a:2 },
  { c:"Rădăcini", q:"Câte rădăcini are incisivul central inferior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are caninul inferior?", o:["1 (rar 2)","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 1 inferior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 2 inferior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 1 inferior?", o:["1","2","3","4"], a:1 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 2 inferior?", o:["1","2","3","4"], a:1 },
  { c:"Rădăcini", q:"Rădăcina molarului 1 inferior are câte canale?", o:["1 canal total","2 canale totale","3 canale (2 mezial + 1 distal)","4 canale"], a:2 },
  { c:"Rădăcini", q:"Rădăcina molarului 1 superior are câte canale?", o:["1 canal","2 canale","3 canale","4 canale"], a:2 },
  { c:"Rădăcini", q:"Care rădăcină a molarului 1 superior este cea mai voluminoasă?", o:["Mezio-vestibulară","Disto-vestibulară","Palatinală","Toate sunt egale"], a:2 },
  { c:"Rădăcini", q:"Care este forma secțiunii la colet a incisivului central inferior?", o:["Circulară","Triunghiulară","De pișcot/clepsidră","Pătrată"], a:2 },
  { c:"Rădăcini", q:"Rădăcina incisivului central superior are secțiune:", o:["Circulară","Triunghiulară","Ovală","Pătrată"], a:1 },
  { c:"Rădăcini", q:"Unde se face separarea rădăcinilor la molarul 1 inferior?", o:["La nivelul apexului","La mijlocul rădăcinii","În imediata vecinătate a coletului","Nu se separă"], a:2 },
  { c:"Rădăcini", q:"Care este direcția de înclinare a apexului la incisivul central inferior?", o:["Lingual","Vestibular","Mezial","Distal"], a:1 },
  { c:"Rădăcini", q:"Care rădăcină a molarului 1 inferior are 2 canale?", o:["Mezială","Distală","Ambele","Niciuna"], a:0 },
  { c:"Rădăcini", q:"Care rădăcină a molarului 1 inferior are 1 canal larg?", o:["Mezială","Distală","Ambele","Niciuna"], a:1 },
  { c:"Rădăcini", q:"Ce formă are secțiunea la colet a rădăcinii incisivului central superior?", o:["Circulară","Triunghi echilateral rotunjit","Ovală alungită","Pătrată"], a:1 },
  { c:"Rădăcini", q:"Ce formă are secțiunea la colet a rădăcinii caninului superior?", o:["Circulară","Triunghi isoscel rotunjit","Ovală","Pătrată"], a:1 },
  { c:"Rădăcini", q:"Ce formă are secțiunea la colet a rădăcinii incisivului lateral superior?", o:["Circulară","Triunghi isoscel rotunjit","Ovală","Pătrată"], a:1 },
  { c:"Rădăcini", q:"Rădăcina incisivului lateral superior are apexul orientat:", o:["Vestibular","Palatinal","Distal","Mezial"], a:2 },
  { c:"Rădăcini", q:"Rădăcina incisivului central superior este orientată cu apexul spre:", o:["Vestibular","Palatinal","Distal","Mezial"], a:2 },
  { c:"Rădăcini", q:"Care este lungimea aproximativă a rădăcinii incisivului central superior?", o:["8-9 mm","12-13 mm","16-17 mm","20-21 mm"], a:1 },
  { c:"Rădăcini", q:"Care este lungimea aproximativă a rădăcinii caninului superior?", o:["12-13 mm","16-17 mm","20-21 mm","25 mm"], a:1 },
  { c:"Rădăcini", q:"Rădăcina premolarului 1 superior are un canal:", o:["Îngust","Larg, uneori 2","Absent","Întotdeauna 3"], a:1 },
  { c:"Rădăcini", q:"Ce formă are secțiunea la colet a premolarului superior?", o:["Circulară","Triunghiulară","Pișcot/clepsidră","Pătrată"], a:2 },
  { c:"Rădăcini", q:"Ce formă are secțiunea la colet a premolarului inferior?", o:["Circulară","Triunghiulară","Pișcot","Ovală"], a:0 },
  { c:"Rădăcini", q:"Apexul rădăcinii premolarului 2 inferior este orientat spre:", o:["Mezial","Distal","Vestibular","Lingual"], a:1 },
  { c:"Rădăcini", q:"Apexul rădăcinii premolarului 1 superior este orientat spre:", o:["Mezial","Distal (discret)","Vestibular","Palatinal"], a:1 },
  { c:"Rădăcini", q:"Unde se separă rădăcinile molarului 1 superior?", o:["La apex","La mijloc","În imediata vecinătate a coletului","Nu se separă"], a:2 },
  { c:"Rădăcini", q:"Rădăcinile molarului 1 superior au apexurile:", o:["Convergente","Divergente cu perimetru apexian mare","Paralele","Fuzionate"], a:1 },
  { c:"Rădăcini", q:"Rădăcinile molarului 2 superior au apexurile:", o:["Mai divergente ca M1","Mai adunate ca M1","Fuzionate","Absente"], a:1 },
  { c:"Rădăcini", q:"Rădăcina molarului 3 superior poate fi:", o:["Unică","Fuzionată într-un monobloc conic","Doar 2 rădăcini","Absentă"], a:1 },
  { c:"Rădăcini", q:"Pe fețele proximale ale rădăcinii incisivului central inferior se află:", o:["Un șanț longitudinal","O creastă","Un cuspid","O fosetă"], a:0 },
  { c:"Rădăcini", q:"Care dinte are cea mai puternică implantare în osul alveolar?", o:["Incisivul central inferior","Caninul superior","Molarul 1 inferior","Premolarul 1 superior"], a:2 },

  // ===== CUSPIZI (20) =====
  { c:"Cuspizi", q:"Câți cuspizi are incisivul central superior?", o:["0 (muchie incizală)","1","2","3"], a:0 },
  { c:"Cuspizi", q:"Câți cuspizi are caninul superior?", o:["1 (muchie cu 2 segmente)","2","3","4"], a:0 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 1 superior?", o:["1","2","3","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 2 superior?", o:["1","2","3","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 1 inferior?", o:["1","2","3 (rar)","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 2 inferior (morfotipul clasic)?", o:["1","2","3","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 1 superior?", o:["3","4","5","6"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 1 inferior?", o:["3","4","5","6"], a:2 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 2 superior?", o:["3","4","5","6"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 2 inferior?", o:["3","4","5","6"], a:1 },
  { c:"Cuspizi", q:"Care este cel mai mare cuspid al molarului 1 superior?", o:["Mezio-vestibular","Disto-vestibular","Mezio-palatinat","Disto-palatinat"], a:2 },
  { c:"Cuspizi", q:"Care este cel mai mic cuspid al molarului 1 superior?", o:["Mezio-vestibular","Disto-vestibular","Mezio-palatinat","Disto-palatinat"], a:3 },
  { c:"Cuspizi", q:"Care este cel mai mare cuspid al molarului 1 inferior?", o:["Mezio-vestibular","Disto-vestibular","Mezio-lingual","Disto-lingual"], a:2 },
  { c:"Cuspizi", q:"Care este cuspidul activ al premolarilor superiori?", o:["Vestibular","Palatinal","Mezial","Distal"], a:1 },
  { c:"Cuspizi", q:"Care este cuspidul activ al premolarilor inferiori?", o:["Vestibular","Lingual","Mezial","Distal"], a:0 },
  { c:"Cuspizi", q:"Care sunt lobii activi ai molarilor superiori?", o:["Vestibulari","Palatinali","Meziali","Distali"], a:1 },
  { c:"Cuspizi", q:"Care sunt lobii activi ai molarilor inferiori?", o:["Vestibulari","Linguali","Meziali","Distali"], a:0 },
  { c:"Cuspizi", q:"Cuspidul mezio-vestibular al molarului 1 superior se aliniază (raport normal) cu:", o:["Șanțul centro-vestibular-mezial al molarului 1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:0 },
  { c:"Cuspizi", q:"Creasta oblică de smalț a molarului 1 superior unește:", o:["Mezio-vestibular cu disto-vestibular","Mezio-palatinat cu disto-vestibular","Mezio-palatinat cu disto-palatinat","Mezio-vestibular cu mezio-palatinat"], a:1 },
  { c:"Cuspizi", q:"Pe ce lob se găsește tuberculul lui Carabelli?", o:["Mezio-vestibular","Disto-vestibular","Mezio-palatinat","Disto-palatinat"], a:2 },
  { c:"Cuspizi", q:"Cuspidul mezio-vestibular al molarului 1 superior este unit cu disto-vestibularul prin:", o:["Șanțul mezio-distal","Creasta oblică de smalț","Creasta marginală","Șanțul disto-palatin"], a:1 },
  { c:"Cuspizi", q:"În ce unghi este deschisă creasta oblică de smalț a molarului 1 superior?", o:["Ascuțit, spre distal","Obtuz, deschis mezial","Drept","Variabil"], a:1 },
  { c:"Cuspizi", q:"La molarul 2 superior, linia oblică de smalț prezintă:", o:["Nicio modificare","O întrerupere în zona centrală","O dublare","O dispariție completă"], a:1 },
  { c:"Cuspizi", q:"Molarul 3 superior cu 3 lobi rezultă prin dispariția lobului:", o:["Mezio-palatinat","Disto-palatinat","Mezio-vestibular","Disto-vestibular"], a:1 },
  { c:"Cuspizi", q:"În morfotipul cu 3 lobi al molarului 3 superior, șanțurile au aspect de:", o:["V","Y","W","X"], a:1 },
  { c:"Cuspizi", q:"În morfotipul cu 3 lobi al molarului 3 superior, lobul palatinal este:", o:["Cel mai mic","Cel mai mare","Egal cu ceilalți","Absent"], a:1 },
  { c:"Cuspizi", q:"Câți lobi are morfotipul clasic al molarului 3 superior?", o:["2","3","4","5"], a:2 },
  { c:"Cuspizi", q:"Cuspidul disto-palatinat al molarului 2 superior este:", o:["Mult mai mare ca mezio-palatinat","Mult mai mic ca mezio-palatinat","Egal","Absent"], a:1 },
  { c:"Cuspizi", q:"La molarul 2 superior, proporția dintre lobul mezio-palatinat și disto-palatinat este:", o:["1/1","2/2","3/4 vs 1/4","1/2 vs 1/2"], a:2 },
  { c:"Cuspizi", q:"Cuspidul mezio-lingual al molarului 1 inferior este:", o:["Cel mai mic","Cel mai mare","Egal cu disto-lingual","Absent"], a:1 },
  { c:"Cuspizi", q:"Ordinea descrescătoare a lobilor molarului 1 inferior este:", o:["ML, DL, MV, CV, DV","MV, ML, DL, CV, DV","DL, ML, MV, CV, DV","Toți egali"], a:0 },
  { c:"Cuspizi", q:"Câți lobi are molarul 2 inferior?", o:["3","4","5","6"], a:1 },
  { c:"Cuspizi", q:"Care este cuspidul cel mai mic al premolarului 1 superior?", o:["Vestibular","Palatinal","Mezial","Distal"], a:1 },
  { c:"Cuspizi", q:"La premolarul 2 superior, cei doi cuspizi sunt:", o:["Vestibular mult mai mare","Palatinal mult mai mare","Aproximativ egali","Unul absent"], a:2 },
  { c:"Cuspizi", q:"La premolarul 1 inferior, raportul între cuspidul vestibular și lingual este:", o:["1/1","2/1","1/2","3/1"], a:1 },
  { c:"Cuspizi", q:"La premolarul 2 inferior cu 3 cuspizi, cuspidul mezio-lingual este:", o:["Cel mai mic","Mai mic ca vestibular, dar mai mare ca disto-lingual","Cel mai mare","Absent"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi poate avea molarul 3 inferior în morfotipul cu 4 lobi?", o:["3","4","5","Variabil"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi poate avea molarul 3 inferior în morfotipul cu 5 lobi?", o:["3","4","5","Variabil"], a:2 },
  { c:"Cuspizi", q:"Caninul superior are marginea incizală formată din:", o:["1 segment","2 segmente inegale (mezial mai scurt, distal mai lung)","3 segmente","4 segmente"], a:1 },
  { c:"Cuspizi", q:"Creasta esențială de smalț pe fața vestibulară a caninului:", o:["Susține cuspidul caninului","Este absentă","Este un șanț","Se află doar pe fața palatinală"], a:0 },

  // ===== ȘANȚURI ȘI FOSETE (15) =====
  { c:"Șanțuri", q:"Câte șanțuri principale are molarul 1 superior?", o:["2","3","4","5"], a:1 },
  { c:"Șanțuri", q:"Câte șanțuri principale are molarul 1 inferior?", o:["2","3","4","5"], a:2 },
  { c:"Șanțuri", q:"Care este forma șanțului mezio-distal al molarului 1 inferior?", o:["Linie dreaptă","Zig-zag","Curbă simplă","Y"], a:1 },
  { c:"Șanțuri", q:"Care este forma șanțului intercuspidian la premolarul 2 inferior cu 3 cuspizi?", o:["V","Y","W","Linie dreaptă"], a:1 },
  { c:"Șanțuri", q:"Șanțul intercuspidian al premolarilor inferiori are convexitatea spre:", o:["Vestibular","Lingual","Mezial","Distal"], a:1 },
  { c:"Șanțuri", q:"Șanțul intercuspidian al premolarilor superiori are direcție:", o:["Vestibulo-palatină","Mezio-distală","Oblice","Verticală"], a:1 },
  { c:"Șanțuri", q:"Câte fosete principale are molarul 1 superior?", o:["1","2","3","4"], a:1 },
  { c:"Șanțuri", q:"Câte fosete principale are molarul 1 inferior?", o:["1","2","3","4"], a:1 },
  { c:"Șanțuri", q:"Unde se află foseta centrală a molarului 1 superior?", o:["Pe fața vestibulară","La intersecția șanțurilor","Pe fața palatinală","Pe creasta marginală"], a:1 },
  { c:"Șanțuri", q:"Șanțul centro-vestibular al molarului 1 superior se termină:", o:["Într-o fosetă pe fața vestibulară","Pierdut pe fața palatinală","Într-o fosetă centrală","Pe creasta marginală"], a:0 },
  { c:"Șanțuri", q:"Șanțul disto-palatin al molarului 1 superior are formă:", o:["Linie dreaptă","Un unghi de 90°","Zig-zag","Curbă"], a:1 },
  { c:"Șanțuri", q:"Ce separă șanțul mezio-distal la molarul 1 inferior?", o:["Cei doi cuspizi vestibular","Cei doi cuspizi linguali","Șirul lobilor vestibulari de cei linguali","Cele 2 creste marginale"], a:2 },
  { c:"Șanțuri", q:"Câte fosete are molarul 1 inferior?", o:["2 principale + 2 accesorii","2 principale + 3 accesorii","1 principală + 2 accesorii","3 principale"], a:1 },
  { c:"Șanțuri", q:"Câte fosete are molarul 1 superior?", o:["2 principale + 1 secundară","3 principale","1 principală + 2 secundare","2 principale + 2 secundare"], a:0 },
  { c:"Șanțuri", q:"Șanțul mezio-central al molarului 1 superior unește:", o:["Foseta mezială cu foseta centrală","Foseta distală cu foseta centrală","Foseta vestibulară cu cea palatinală","Cele 2 creste marginale"], a:0 },
  { c:"Șanțuri", q:"Șanțul mezio-distal al molarului 1 inferior separă:", o:["Cei 2 cuspizi vestibular","Cei 2 cuspizi linguali","Lobii vestibulari de cei linguali","Cele 2 creste marginale"], a:2 },
  { c:"Șanțuri", q:"Șanțul centro-lingual al molarului 1 inferior are orientare:", o:["Mezio-distală","Vestibulo-linguală","Oblică","Verticală"], a:1 },
  { c:"Șanțuri", q:"Șanțul centro-vestibular mezial al molarului 1 inferior separă:", o:["Cei 2 cuspizi vestibulari (MV și CV)","Cei 2 cuspizi linguali","Cresta marginală","Foseta centrală"], a:0 },
  { c:"Șanțuri", q:"Șanțul centro-vestibular distal al molarului 1 inferior separă:", o:["Cei 2 cuspizi vestibulari (CV și DV)","Cei 2 cuspizi linguali","Cresta marginală","Foseta centrală"], a:0 },
  { c:"Șanțuri", q:"Șanțul mezio-central al molarului 1 superior separă:", o:["Lobul MV de lobul MP","Lobul MV de lobul DV","Lobul MP de lobul DP","Cele 2 creste marginale"], a:0 },
  { c:"Șanțuri", q:"Șanțul centro-vestibular al molarului 1 superior separă:", o:["Lobul MV de lobul DV","Lobul MV de lobul MP","Lobul MP de lobul DP","Cei 2 cuspizi palatinali"], a:0 },
  { c:"Șanțuri", q:"Primul segment al șanțului disto-palatin al molarului 1 superior separă:", o:["Lobul DV de lobul DP","Lobul MV de lobul MP","Lobul MV de lobul DV","Cei 2 cuspizi palatinali"], a:0 },
  { c:"Șanțuri", q:"Al doilea segment al șanțului disto-palatin al molarului 1 superior separă:", o:["Lobul MP de lobul DP","Lobul MV de lobul MP","Lobul DV de lobul DP","Cei 2 cuspizi palatinali"], a:0 },
  { c:"Șanțuri", q:"Ce unghi face șanțul disto-palatin al molarului 1 superior între cele 2 segmente?", o:["45°","60°","90°","180°"], a:2 },
  { c:"Șanțuri", q:"Șanțul intercuspidian al premolarului 1 superior este situat:", o:["În centrul feței ocluzale","Spre palatinal","Spre vestibular","Pe creasta marginală"], a:1 },
  { c:"Șanțuri", q:"Șanțul intercuspidian al premolarului 2 superior este situat:", o:["Spre palatinal","În centrul feței ocluzale (împarte în 2 părți egale)","Spre vestibular","Pe creasta marginală"], a:1 },
  { c:"Șanțuri", q:"Șanțul intercuspidian al premolarului 1 inferior are convexitatea spre:", o:["Vestibular","Lingual","Mezial","Distal"], a:1 },
  { c:"Șanțuri", q:"Câte șanțuri are molarul 2 inferior?", o:["1","2","3","4"], a:1 },
  { c:"Șanțuri", q:"Șanțul molarului 2 inferior are forma:", o:["Linie dreaptă","În cruce (formează un unghi drept)","Zig-zag","Curbă simplă"], a:1 },
  { c:"Șanțuri", q:"Foseta centrală a molarului 2 inferior se află la:", o:["Intersecția celor 2 șanțuri","Marginea mezială","Marginea distală","Fața vestibulară"], a:0 },

  // ===== ALINIERE ȘI OCLUZIE (15) =====
  { c:"Aliniere", q:"Câți dinți vin în contact cu câte doi antagoniști (unitate masticatorie)?", o:["Toți dinții","Toți, exceptând incisivii centrali inferiori și molarii 3 superiori","Doar molarii","Doar premolarii"], a:1 },
  { c:"Aliniere", q:"Cuspidul mezio-vestibular al molarului 1 superior se aliniază (Clasa I Angle) cu:", o:["Șanțul centro-vestibular-mezial al molarului 1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:0 },
  { c:"Aliniere", q:"Clasa II Angle (distalizat) înseamnă că cuspidul MV al M1 superior se aliniază cu:", o:["Șanțul centro-vestibular al M1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:1 },
  { c:"Aliniere", q:"Clasa III Angle (mezializat) înseamnă că cuspidul MV al M1 superior se aliniază cu:", o:["Șanțul centro-vestibular al M1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:2 },
  { c:"Aliniere", q:"Curba lui Spee se referă la planul:", o:["Transversal","Sagital","Frontal","Orizontal"], a:1 },
  { c:"Aliniere", q:"Curba lui Wilson se referă la planul:", o:["Transversal","Sagital","Frontal","Orizontal"], a:0 },
  { c:"Aliniere", q:"Adâncimea maximă a curbei lui Spee este la nivelul:", o:["Premolarului 1 inferior","Primului molar inferior permanent","Molarului 2 inferior","Caninului inferior"], a:1 },
  { c:"Aliniere", q:"Înălțimea triunghiului curbei transversale la arcadele cu morfologie primară este de:", o:["2 mm","3 mm","5 mm","8 mm"], a:2 },
  { c:"Aliniere", q:"Stopurile ocluzale Clasa I sunt reprezentate de:", o:["Marginile libere ale incisivilor inferiori","Cuspizii vestibulari ai premolarilor și molarilor mandibulari","Cuspizii palatinali ai premolarilor și molarilor superiori","Caninii superiori"], a:1 },
  { c:"Aliniere", q:"Stopurile ocluzale Clasa a II-a sunt reprezentate de:", o:["Marginile libere ale incisivilor inferiori","Cuspizii vestibulari ai premolarilor și molarilor mandibulari","Cuspizii palatinali ai premolarilor și molarilor superiori","Caninii superiori"], a:0 },
  { c:"Aliniere", q:"Stopurile ocluzale Clasa a III-a sunt reprezentate de:", o:["Marginile libere ale incisivilor inferiori","Cuspizii vestibulari ai premolarilor și molarilor mandibulari","Cuspizii palatinali ai premolarilor și molarilor superiori","Caninii inferiori"], a:2 },
  { c:"Aliniere", q:"Supraacoperirea (overbite) reprezintă distanța:", o:["Verticală dintre marginile incizale","Orizontală între incisivi","Unghiulară","Diagonală"], a:0 },
  { c:"Aliniere", q:"Surplombul (overjet) reprezintă distanța:", o:["Verticală","În plan medio-sagital","Unghiulară","Diagonală"], a:1 },
  { c:"Aliniere", q:"Raportul labiodont prezintă:", o:["Acoperire = 0, surplomb = 0","Acoperire > 3 mm","Acoperire negativă","Surplomb > 5 mm"], a:0 },
  { c:"Aliniere", q:"Cuspidul mezio-vestibular al molarului 1 superior se aliniază cu șanțul centro-vestibular-mezial al molarului 1 inferior. Aceasta este Clasa:", o:["I Angle","II Angle","III Angle","IV Angle"], a:0 },
  { c:"Aliniere", q:"Unitatea masticatorie reprezintă contactul unui dinte cu:", o:["1 antagonist","2 antagoniști","3 antagoniști","4 antagoniști"], a:1 },
  { c:"Aliniere", q:"Care dinte face excepție de la regula unității masticatorii?", o:["Incisivul central inferior","Incisivul central superior","Caninul inferior","Molarul 1 inferior"], a:0 },
  { c:"Aliniere", q:"Care molari fac excepție de la regula unității masticatorii?", o:["Molarii 1 inferiori","Molarii 3 superiori","Molarii 2 inferiori","Molarii 1 superiori"], a:1 },
  { c:"Aliniere", q:"Liniile mediane ale celor două arcade se găsesc:", o:["În planuri diferite","În același plan sagital","Decalate","Oblice"], a:1 },
  { c:"Aliniere", q:"Fețele distale ale ultimilor molari se găsesc:", o:["În planuri diferite","În același plan frontal","Decalate","Oblice"], a:1 },
  { c:"Aliniere", q:"Cuspizii vestibulari ai dinților laterali superiori sunt situați:", o:["În interiorul cuspizilor inferiori","În afara cuspizilor vestibulari inferiori","Aliniați","Decalați mezial"], a:1 },
  { c:"Aliniere", q:"Cuspizii linguali ai dinților laterali inferiori sunt situați:", o:["Vestibular față de cei palatinali superiori","Oral față de cuspizii palatinali superiori","Aliniați","Decalați distal"], a:1 },
  { c:"Aliniere", q:"Curba lui Spee este dată de unirea:", o:["Cuspizilor vestibulari ai dinților laterali mandibulari","Cuspizilor linguali","Marginilor incizale","Fețelor proximale"], a:0 },
  { c:"Aliniere", q:"Adâncimea curbei lui Spee este de:", o:["1-3 mm","3-5 mm","5-7 mm","7-9 mm"], a:0 },
  { c:"Aliniere", q:"Concavitatea curbei lui Spee este orientată spre:", o:["Mandibulă","Maxilar","Vestibular","Lingual"], a:1 },
  { c:"Aliniere", q:"Curba lui Wilson rezultă prin unirea:", o:["Cuspizilor vestibulari cu cei linguali ai molarilor 1 inferiori","Marginilor incizale","Fețelor proximale","Crestelor marginale"], a:0 },
  { c:"Aliniere", q:"Curba lui Wilson este curbă de compensație pentru:", o:["Mișcările de lateralitate ale condililor mandibulari","Mișcările de deschidere","Mișcările de protruzie","Deglutiție"], a:0 },
  { c:"Aliniere", q:"Inversarea curbei lui Wilson apare prin:", o:["Abraziunea cuspizilor activi vestibulari ai dinților laterali mandibulari","Abraziunea cuspizilor linguali","Creștere osoasă","Erupție tardivă"], a:0 },
  { c:"Aliniere", q:"Cheia de ocluzie a lui Angle se bazează pe relația dintre:", o:["Caninii superiori și inferiori","Molarul 1 superior și molarul 1 inferior","Premolari","Incisivii centrali"], a:1 },
  { c:"Aliniere", q:"Ce plan de referință împarte arcadele în hemiarcade dreapta/stânga?", o:["Planul frontal","Planul medio-sagital","Planul transversal","Planul ocluzal"], a:1 },

  // ===== ASPECT ȘI FORMĂ (15) =====
  { c:"Aspect", q:"Care este forma generală a coroanei incisivului central superior?", o:["Lopată/scafă","Cuboidă","Piramidală","Ovoidă"], a:0 },
  { c:"Aspect", q:"Care este forma generală a coroanei caninului superior?", o:["Lopată","Cuboidă","Piramidală (vârf de lance)","Ovoidă"], a:2 },
  { c:"Aspect", q:"Care este forma generală a coroanei molarului 1 superior?", o:["Lopată","Cuboidă (aplatizată M-D)","Piramidală","Ovoidă"], a:1 },
  { c:"Aspect", q:"Care este forma generală a coroanei molarului 1 inferior?", o:["Lopată","Paralelipiped dreptunghic (aplatizat V-L)","Piramidală","Ovoidă"], a:1 },
  { c:"Aspect", q:"Ce este cingulumul?", o:["O creastă vestibulară","O formațiune hemisferică pe fața palatinală/linguală","Marginea incizală","Un șanț interlobular"], a:1 },
  { c:"Aspect", q:"Pe ce dinți se găsește cingulumul?", o:["Doar pe molari","Pe toți dinții frontali","Doar pe incisivi","Doar pe canini"], a:1 },
  { c:"Aspect", q:"Culoarea coroanei incisivilor superiori este repartizată pe:", o:["2 zone","3 zone (galben, alb-gri, transparent)","4 zone","Uniform"], a:1 },
  { c:"Aspect", q:"Ce este foramen caecum?", o:["Un șanț","O fosetă mică pe fața palatinală a incisivului lateral superior","Un cuspid","O creastă"], a:1 },
  { c:"Aspect", q:"Ce este ecuatorul anatomic?", o:["Linia de maximă convexitate a fețelor laterale","Linia coletului","Marginea incizală","Linia mediană"], a:0 },
  { c:"Aspect", q:"Ce este perimetrul ocluzal?", o:["Suma crestelor sagitale + crestele marginale","Marginea coletului","Linia mediană","Marginea incizală"], a:0 },
  { c:"Aspect", q:"Ce este lacul ocluzal?", o:["Spațiul interior perimetrului ocluzal","Foseta centrală","Șanțul principal","Creasta marginală"], a:0 },
  { c:"Aspect", q:"Ce este tuberculul lui Carabelli?", o:["Un cuspid normal","Un tubercul inconstant pe lobul mezio-palatin al molarului 1 superior","O fosetă","Un șanț"], a:1 },
  { c:"Aspect", q:"Ce este tuberculul lui Bolk?", o:["Un cuspid normal","Un tubercul inconstant pe lobul mezio-vestibular al molarului 2 inferior","O fosetă","Un șanț"], a:1 },
  { c:"Aspect", q:"Ce este creasta oblică de smalț?", o:["O creastă care unește mezio-palatinat cu disto-vestibular (M1 sup)","O creastă vestibulară","O margine incizală","Un șanț"], a:0 },
  { c:"Aspect", q:"Ce reprezintă punctul de contact?", o:["Locul unde se ating doi dinți vecini prin fețele proximale","Vârful cuspidului","Marginea incizală","Linia mediană"], a:0 },
  { c:"Aspect", q:"Ce formă geometrică are coroana incisivului central inferior?", o:["Lopată/daltă aplatizată V-L","Cuboidă","Piramidală","Ovoidă"], a:0 },
  { c:"Aspect", q:"Ce formă geometrică are coroana premolarului superior?", o:["Lopată","Paralelipipedică aplatizată M-D","Piramidală","Cuboidă"], a:1 },
  { c:"Aspect", q:"Ce formă geometrică are coroana premolarului inferior?", o:["Lopată","Globuloasă","Piramidală","Cuboidă"], a:1 },
  { c:"Aspect", q:"Raportul lungime/lățime al coroanei incisivilor inferiori este de:", o:["1/1","2/1","3/1","1/2"], a:1 },
  { c:"Aspect", q:"Raportul lungime/lățime al coroanei incisivilor superiori este de:", o:["Aproape 1/1","2/1","3/1","1/2"], a:0 },
  { c:"Aspect", q:"Ce element morfologic caracterizează fața palatinală a incisivilor superiori?", o:["Cingulumul bine evidențiat","Absența cingulumului","Un cuspid","Un șanț profund"], a:0 },
  { c:"Aspect", q:"Relieful lingual al incisivilor inferiori este:", o:["Foarte proeminent","Foarte șters, abia perceptibil","Identic cu cel vestibular","Absent"], a:1 },
  { c:"Aspect", q:"Pe ce lob al molarului 1 superior se poate găsi tuberculul lui Carabelli?", o:["Mezio-vestibular","Disto-vestibular","Mezio-palatinat","Disto-palatinat"], a:2 },
  { c:"Aspect", q:"Pe ce lob al molarului 2 inferior se poate găsi tuberculul lui Bolk?", o:["Mezio-lingual","Disto-lingual","Mezio-vestibular","Disto-vestibular"], a:2 },
  { c:"Aspect", q:"Ce este nișa masticatorie?", o:["Spațiul triunghiular deschis spre ocluzal între doi dinți vecini","O fosetă","Un șanț","O creastă"], a:0 },
  { c:"Aspect", q:"Ce este spațiul papilar?", o:["Spațiul triunghiular sub punctul de contact, cu baza spre os","O fosetă","Un șanț","Un cuspid"], a:0 },
  { c:"Aspect", q:"Ecuatorul protetic (de implantare) are importanță în:", o:["Protetica dentară","Endodonție","Parodontologie","Ortodonție"], a:0 },
  { c:"Aspect", q:"Ce este lobul dentar?", o:["Unitatea embriologică a coroanei dentare","Un cuspid","Un șanț","O creastă"], a:0 },
  { c:"Aspect", q:"Ce elemente morfologice are un cuspid?", o:["4 muchii (2 sagitale + 2 transversale) și 1 vârf","2 muchii și 1 vârf","3 muchii","Fără muchii"], a:0 },
  { c:"Aspect", q:"Ce este creasta esențială (transversală)?", o:["O creastă perpendiculară pe creasta ocluzală","O creastă paralelă cu muchia incizală","O margine","Un șanț"], a:0 }
];
