// ============================================================
// BANCA DE ÎNTREBĂRI - Morfologie Dentară
// Focus: aliniere, aspect, compoziție, rădăcini, cuspizi, șanțuri
// ============================================================
const QUESTIONS = [
  // ===== COMPOZIȚIE ȚESUTURI (15) =====
  { c:"Compoziție", q:"Care este compoziția procentuală a smalțului?", o:["95% hidroxiapatită, 4% apă, 1% organice","70% hidroxiapatită, 12% apă, 18% organice","65% hidroxiapatită, 23% organice, 12% apă","50% hidroxiapatită, 25% apă, 25% organice"], a:0 },
  { c:"Compoziție", q:"Care este compoziția procentuală a dentinei?", o:["95% anorganic, 4% apă, 1% organic","70% anorganic, 12% apă, 18% organic","65% anorganic, 23% organic, 12% apă","80% anorganic, 10% apă, 10% organic"], a:1 },
  { c:"Compoziție", q:"Care este compoziția procentuală a cementului?", o:["95% hidroxiapatită, 4% apă, 1% organice","70% hidroxiapatită, 12% apă, 18% organice","65% hidroxiapatită, 23% organice, 12% apă","50% hidroxiapatită, 25% apă, 25% organice"], a:2 },
  { c:"Compoziție", q:"Care țesut dentar este cel mai dur din organism?", o:["Dentina","Cementul","Smalțul","Pulpa"], a:2 },
  { c:"Compoziție", q:"Care țesut dentar are cea mai apropiată structură de țesutul osos?", o:["Smalțul","Dentina","Cementul","Pulpa"], a:2 },
  { c:"Compoziție", q:"Care țesut dentar se formează DOAR în perioada embrionară?", o:["Dentina","Cementul","Smalțul","Pulpa"], a:2 },
  { c:"Compoziție", q:"Care țesut se formează pe toată durata vieții dintelui?", o:["Smalțul","Dentina și cementul","Doar smalțul","Doar cementul"], a:1 },
  { c:"Compoziție", q:"Smalțul este sintetizat de:", o:["Odontoblaste","Ameloblaste","Cementoblaști","Fibroblaști"], a:1 },
  { c:"Compoziție", q:"Dentina este sintetizată de:", o:["Odontoblaste","Ameloblaste","Cementoblaști","Fibroblaști"], a:0 },
  { c:"Compoziție", q:"Cementul este sintetizat de:", o:["Odontoblaste","Ameloblaste","Cementoblaști","Fibroblaști"], a:2 },
  { c:"Compoziție", q:"Smalțul provine embriologic din:", o:["Mezoderm","Ectoderm","Endoderm","Mezenchim"], a:1 },
  { c:"Compoziție", q:"Dentina și cementul provin embriologic din:", o:["Ectoderm","Mezoderm","Endoderm","Neuroectoderm"], a:1 },
  { c:"Compoziție", q:"Care este grosimea smalțului la nivelul cuspizilor?", o:["0,5 mm","1 mm","1,5 mm","2,5 mm"], a:3 },
  { c:"Compoziție", q:"Care este grosimea smalțului la nivelul coletului?", o:["0,5 mm","1 mm","1,5 mm","2,5 mm"], a:0 },
  { c:"Compoziție", q:"Dentina terțiară se formează:", o:["În timpul odontogenezei","Fiziologic după odontogeneză","Ca mecanism de apărare la stimuli patologici","Doar embrionar"], a:2 },

  // ===== RĂDĂCINI (20) =====
  { c:"Rădăcini", q:"Câte rădăcini are incisivul central superior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are incisivul lateral superior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are caninul superior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 1 superior?", o:["1 (uneori 2)","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 2 superior?", o:["1 (uneori 2)","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 1 superior?", o:["1","2","3","4"], a:2 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 2 superior?", o:["1","2","3","4"], a:2 },
  { c:"Rădăcini", q:"Câte rădăcini are incisivul central inferior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are caninul inferior?", o:["1 (rar 2)","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 1 inferior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are premolarul 2 inferior?", o:["1","2","3","4"], a:0 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 1 inferior?", o:["1","2","3","4"], a:1 },
  { c:"Rădăcini", q:"Câte rădăcini are molarul 2 inferior?", o:["1","2","3","4"], a:1 },
  { c:"Rădăcini", q:"Rădăcina molarului 1 inferior are câte canale?", o:["1 canal total","2 canale totale","3 canale (2 mezial + 1 distal)","4 canale"], a:2 },
  { c:"Rădăcini", q:"Rădăcina molarului 1 superior are câte canale?", o:["1 canal","2 canale","3 canale","4 canale"], a:2 },
  { c:"Rădăcini", q:"Care rădăcină a molarului 1 superior este cea mai voluminoasă?", o:["Mezio-vestibulară","Disto-vestibulară","Palatinală","Toate sunt egale"], a:2 },
  { c:"Rădăcini", q:"Care este forma secțiunii la colet a incisivului central inferior?", o:["Circulară","Triunghiulară","De pișcot/clepsidră","Pătrată"], a:2 },
  { c:"Rădăcini", q:"Rădăcina incisivului central superior are secțiune:", o:["Circulară","Triunghiulară","Ovală","Pătrată"], a:1 },
  { c:"Rădăcini", q:"Unde se face separarea rădăcinilor la molarul 1 inferior?", o:["La nivelul apexului","La mijlocul rădăcinii","În imediata vecinătate a coletului","Nu se separă"], a:2 },
  { c:"Rădăcini", q:"Care este direcția de înclinare a apexului la incisivul central inferior?", o:["Lingual","Vestibular","Mezial","Distal"], a:1 },

  // ===== CUSPIZI (20) =====
  { c:"Cuspizi", q:"Câți cuspizi are incisivul central superior?", o:["0 (muchie incizală)","1","2","3"], a:0 },
  { c:"Cuspizi", q:"Câți cuspizi are caninul superior?", o:["1 (muchie cu 2 segmente)","2","3","4"], a:0 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 1 superior?", o:["1","2","3","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 2 superior?", o:["1","2","3","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 1 inferior?", o:["1","2","3 (rar)","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are premolarul 2 inferior (morfotipul clasic)?", o:["1","2","3","4"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 1 superior?", o:["3","4","5","6"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 1 inferior?", o:["3","4","5","6"], a:2 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 2 superior?", o:["3","4","5","6"], a:1 },
  { c:"Cuspizi", q:"Câți cuspizi are molarul 2 inferior?", o:["3","4","5","6"], a:1 },
  { c:"Cuspizi", q:"Care este cel mai mare cuspid al molarului 1 superior?", o:["Mezio-vestibular","Disto-vestibular","Mezio-palatinat","Disto-palatinat"], a:2 },
  { c:"Cuspizi", q:"Care este cel mai mic cuspid al molarului 1 superior?", o:["Mezio-vestibular","Disto-vestibular","Mezio-palatinat","Disto-palatinat"], a:3 },
  { c:"Cuspizi", q:"Care este cel mai mare cuspid al molarului 1 inferior?", o:["Mezio-vestibular","Disto-vestibular","Mezio-lingual","Disto-lingual"], a:2 },
  { c:"Cuspizi", q:"Care este cuspidul activ al premolarilor superiori?", o:["Vestibular","Palatinal","Mezial","Distal"], a:1 },
  { c:"Cuspizi", q:"Care este cuspidul activ al premolarilor inferiori?", o:["Vestibular","Lingual","Mezial","Distal"], a:0 },
  { c:"Cuspizi", q:"Care sunt lobii activi ai molarilor superiori?", o:["Vestibulari","Palatinali","Meziali","Distali"], a:1 },
  { c:"Cuspizi", q:"Care sunt lobii activi ai molarilor inferiori?", o:["Vestibulari","Linguali","Meziali","Distali"], a:0 },
  { c:"Cuspizi", q:"Cuspidul mezio-vestibular al molarului 1 superior se aliniază (raport normal) cu:", o:["Șanțul centro-vestibular-mezial al molarului 1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:0 },
  { c:"Cuspizi", q:"Creasta oblică de smalț a molarului 1 superior unește:", o:["Mezio-vestibular cu disto-vestibular","Mezio-palatinat cu disto-vestibular","Mezio-palatinat cu disto-palatinat","Mezio-vestibular cu mezio-palatinat"], a:1 },
  { c:"Cuspizi", q:"Pe ce lob se găsește tuberculul lui Carabelli?", o:["Mezio-vestibular","Disto-vestibular","Mezio-palatinat","Disto-palatinat"], a:2 },

  // ===== ȘANȚURI ȘI FOSETE (15) =====
  { c:"Șanțuri", q:"Câte șanțuri principale are molarul 1 superior?", o:["2","3","4","5"], a:1 },
  { c:"Șanțuri", q:"Câte șanțuri principale are molarul 1 inferior?", o:["2","3","4","5"], a:2 },
  { c:"Șanțuri", q:"Care este forma șanțului mezio-distal al molarului 1 inferior?", o:["Linie dreaptă","Zig-zag","Curbă simplă","Y"], a:1 },
  { c:"Șanțuri", q:"Care este forma șanțului intercuspidian la premolarul 2 inferior cu 3 cuspizi?", o:["V","Y","W","Linie dreaptă"], a:1 },
  { c:"Șanțuri", q:"Șanțul intercuspidian al premolarilor inferiori are convexitatea spre:", o:["Vestibular","Lingual","Mezial","Distal"], a:1 },
  { c:"Șanțuri", q:"Șanțul intercuspidian al premolarilor superiori are direcție:", o:["Vestibulo-palatină","Mezio-distală","Oblice","Verticală"], a:1 },
  { c:"Șanțuri", q:"Câte fosete principale are molarul 1 superior?", o:["1","2","3","4"], a:1 },
  { c:"Șanțuri", q:"Câte fosete principale are molarul 1 inferior?", o:["1","2","3","4"], a:1 },
  { c:"Șanțuri", q:"Unde se află foseta centrală a molarului 1 superior?", o:["Pe fața vestibulară","La intersecția șanțurilor","Pe fața palatinală","Pe creasta marginală"], a:1 },
  { c:"Șanțuri", q:"Șanțul centro-vestibular al molarului 1 superior se termină:", o:["Într-o fosetă pe fața vestibulară","Pierdut pe fața palatinală","Într-o fosetă centrală","Pe creasta marginală"], a:0 },
  { c:"Șanțuri", q:"Șanțul disto-palatin al molarului 1 superior are formă:", o:["Linie dreaptă","Un unghi de 90°","Zig-zag","Curbă"], a:1 },
  { c:"Șanțuri", q:"Ce separă șanțul mezio-distal la molarul 1 inferior?", o:["Cei doi cuspizi vestibular","Cei doi cuspizi linguali","Șirul lobilor vestibulari de cei linguali","Cele 2 creste marginale"], a:2 },
  { c:"Șanțuri", q:"Câte fosete are molarul 1 inferior?", o:["2 principale + 2 accesorii","2 principale + 3 accesorii","1 principală + 2 accesorii","3 principale"], a:1 },
  { c:"Șanțuri", q:"Câte fosete are molarul 1 superior?", o:["2 principale + 1 secundară","3 principale","1 principală + 2 secundare","2 principale + 2 secundare"], a:0 },
  { c:"Șanțuri", q:"Șanțul mezio-central al molarului 1 superior unește:", o:["Foseta mezială cu foseta centrală","Foseta distală cu foseta centrală","Foseta vestibulară cu cea palatinală","Cele 2 creste marginale"], a:0 },

  // ===== ALINIERE ȘI OCLUZIE (15) =====
  { c:"Aliniere", q:"Câți dinți vin în contact cu câte doi antagoniști (unitate masticatorie)?", o:["Toți dinții","Toți, exceptând incisivii centrali inferiori și molarii 3 superiori","Doar molarii","Doar premolarii"], a:1 },
  { c:"Aliniere", q:"Cuspidul mezio-vestibular al molarului 1 superior se aliniază (Clasa I Angle) cu:", o:["Șanțul centro-vestibular-mezial al molarului 1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:0 },
  { c:"Aliniere", q:"Clasa II Angle (distalizat) înseamnă că cuspidul MV al M1 superior se aliniază cu:", o:["Șanțul centro-vestibular al M1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:1 },
  { c:"Aliniere", q:"Clasa III Angle (mezializat) înseamnă că cuspidul MV al M1 superior se aliniază cu:", o:["Șanțul centro-vestibular al M1 inferior","Abrazura M1-P2 inferior","Abrazura M1-M2 inferior","Vârful caninului inferior"], a:2 },
  { c:"Aliniere", q:"Curba lui Spee se referă la planul:", o:["Transversal","Sagital","Frontal","Orizontal"], a:1 },
  { c:"Aliniere", q:"Curba lui Wilson se referă la planul:", o:["Transversal","Sagital","Frontal","Orizontal"], a:0 },
  { c:"Aliniere", q:"Adâncimea maximă a curbei lui Spee este la nivelul:", o:["Premolarului 1 inferior","Primului molar inferior permanent","Molarului 2 inferior","Caninului inferior"], a:1 },
  { c:"Aliniere", q:"Înălțimea triunghiului curbei transversale la arcadele cu morfologie primară este de:", o:["2 mm","3 mm","5 mm","8 mm"], a:2 },
  { c:"Aliniere", q:"Stopurile ocluzale Clasa I sunt reprezentate de:", o:["Marginile libere ale incisivilor inferiori","Cuspizii vestibulari ai premolarilor și molarilor mandibulari","Cuspizii palatinali ai premolarilor și molarilor superiori","Caninii superiori"], a:1 },
  { c:"Aliniere", q:"Stopurile ocluzale Clasa a II-a sunt reprezentate de:", o:["Marginile libere ale incisivilor inferiori","Cuspizii vestibulari ai premolarilor și molarilor mandibulari","Cuspizii palatinali ai premolarilor și molarilor superiori","Caninii superiori"], a:0 },
  { c:"Aliniere", q:"Stopurile ocluzale Clasa a III-a sunt reprezentate de:", o:["Marginile libere ale incisivilor inferiori","Cuspizii vestibulari ai premolarilor și molarilor mandibulari","Cuspizii palatinali ai premolarilor și molarilor superiori","Caninii inferiori"], a:2 },
  { c:"Aliniere", q:"Supraacoperirea (overbite) reprezintă distanța:", o:["Verticală dintre marginile incizale","Orizontală între incisivi","Unghiulară","Diagonală"], a:0 },
  { c:"Aliniere", q:"Surplombul (overjet) reprezintă distanța:", o:["Verticală","În plan medio-sagital","Unghiulară","Diagonală"], a:1 },
  { c:"Aliniere", q:"Raportul labiodont prezintă:", o:["Acoperire = 0, surplomb = 0","Acoperire > 3 mm","Acoperire negativă","Surplomb > 5 mm"], a:0 },
  { c:"Aliniere", q:"Cuspidul mezio-vestibular al molarului 1 superior se aliniază cu șanțul centro-vestibular-mezial al molarului 1 inferior. Aceasta este Clasa:", o:["I Angle","II Angle","III Angle","IV Angle"], a:0 },

  // ===== ASPECT ȘI FORMĂ (15) =====
  { c:"Aspect", q:"Care este forma generală a coroanei incisivului central superior?", o:["Lopată/scafă","Cuboidă","Piramidală","Ovoidă"], a:0 },
  { c:"Aspect", q:"Care este forma generală a coroanei caninului superior?", o:["Lopată","Cuboidă","Piramidală (vârf de lance)","Ovoidă"], a:2 },
  { c:"Aspect", q:"Care este forma generală a coroanei molarului 1 superior?", o:["Lopată","Cuboidă (aplatizată M-D)","Piramidală","Ovoidă"], a:1 },
  { c:"Aspect", q:"Care este forma generală a coroanei molarului 1 inferior?", o:["Lopată","Paralelipiped dreptunghic (aplatizat V-L)","Piramidală","Ovoidă"], a:1 },
  { c:"Aspect", q:"Ce este cingulumul?", o:["O creastă vestibulară","O formațiune hemisferică pe fața palatinală/linguală","Marginea incizală","Un șanț interlobular"], a:1 },
  { c:"Aspect", q:"Pe ce dinți se găsește cingulumul?", o:["Doar pe molari","Pe toți dinții frontali","Doar pe incisivi","Doar pe canini"], a:1 },
  { c:"Aspect", q:"Culoarea coroanei incisivilor superiori este repartizată pe:", o:["2 zone","3 zone (galben, alb-gri, transparent)","4 zone","Uniform"], a:1 },
  { c:"Aspect", q:"Ce este foramen caecum?", o:["Un șanț","O fosetă mică pe fața palatinală a incisivului lateral superior","Un cuspid","O creastă"], a:1 },
  { c:"Aspect", q:"Ce este ecuatorul anatomic?", o:["Linia de maximă convexitate a fețelor laterale","Linia coletului","Marginea incizală","Linia mediană"], a:0 },
  { c:"Aspect", q:"Ce este perimetrul ocluzal?", o:["Suma crestelor sagitale + crestele marginale","Marginea coletului","Linia mediană","Marginea incizală"], a:0 },
  { c:"Aspect", q:"Ce este lacul ocluzal?", o:["Spațiul interior perimetrului ocluzal","Foseta centrală","Șanțul principal","Creasta marginală"], a:0 },
  { c:"Aspect", q:"Ce este tuberculul lui Carabelli?", o:["Un cuspid normal","Un tubercul inconstant pe lobul mezio-palatin al molarului 1 superior","O fosetă","Un șanț"], a:1 },
  { c:"Aspect", q:"Ce este tuberculul lui Bolk?", o:["Un cuspid normal","Un tubercul inconstant pe lobul mezio-vestibular al molarului 2 inferior","O fosetă","Un șanț"], a:1 },
  { c:"Aspect", q:"Ce este creasta oblică de smalț?", o:["O creastă care unește mezio-palatinat cu disto-vestibular (M1 sup)","O creastă vestibulară","O margine incizală","Un șanț"], a:0 },
  { c:"Aspect", q:"Ce reprezintă punctul de contact?", o:["Locul unde se ating doi dinți vecini prin fețele proximale","Vârful cuspidului","Marginea incizală","Linia mediană"], a:0 }
];
